# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anderson Santos
title: Analista Judiciário do Tribunal Regional do Trabalho da 6ª Região
email: andssuu@gmail.com
website: andssuu.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: Anderso96625672
github_username:  andssuu
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: andssuu
linkedin_username: andssuu
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Sobre
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
              Um rapaz latino-americano <br>
              sem dinheiro no banco <br>
              sem parentes importantes <br>
              e vindo do interior.

content:
  - title: Experiência Profissional # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tribunal Regional do Trabalho da 6ª Região
        link: https://www.trt6.jus.br
        link_text: trt6.jus.br
        sub_title: Analista Judiciário - Tecnologia da Informação
        caption: Junho 2023 - Presente
        description: | # this will include new lines to allow paragraphs
                  Alocado na seção de Monitoramento dos Serviços de TIC, atualmente trabalho com o 
                  monitoramento e a implantação em produção das aplicações regionais, nacionais e PJe.

                  Tecnologias: Kubernetes, Ansible, Elasticsearch, Grafana, Zabbix, Fluentd, Prometheus Kibana, Git, Shell script e Python.
      - layout: left
        title: Universidade Federal Rural de Pernambuco
        link: http://ufrpe.br
        link_text: ufrpe.br
        sub_title: Analista de Sistemas - Suporte e Rede
        caption: Janeiro 2019 - 2023
        description: | # this will include new lines to allow paragraphs
                Na coordenadoria de Redes e Conectividade, trabalhei na gerência e monitoramento dos ativos de rede.
              
                Na coordenadoria de Sistemas Computacionais, tive a oportunidade de trabalhar com gestão e automação de aplicações.

                Tecnologias: switch L2 e L3 (Cisco, HP e 3Com), Controladora Wi-Fi Cisco, Firewall (Iptables, Fortigate, Juniper), Zabbix, Git, Shell script, Python, Linux, Google Workspace, Kubernetes, Zimbra, Servidores Web e Servidores de Aplicações.
      - layout: left
        title: Ello Político
        link: http://ellopolitico.com.br
        link_text: ellopolitico.com.br
        sub_title: Desenvolvedor Full Stack
        caption: Outubro 2016 - 2017
        description: | # this will include new lines to allow paragraphs
                Desenvolvimento web (frontend e backend).

                Tecnologias: Django, Python, Git, HTML, CSS, Javascript.
      - layout: left
        title: Simbiose Ventures
        link: https://www.simbioseventures.com
        link_text: simbioseventures.com.br
        sub_title: Estágio Acadêmico
        caption: 2016
        description: | # this will include new lines to allow paragraphs
                Desenvolvimento web (frontend e backend).

                Tecnologias: Django, Python, Git, HTML, CSS, Javascript.

  - title: Formação Acadêmica # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Mestrado em Informática Aplicada
        caption: 2020 - 2022
        sub_title: Universidade Federal Rural de Pernambuco
        description: | # this will include new lines to allow paragraphs
                Classificação do comportamento de bovinos por meio de sensores inerciais: uma abordagem com aprendizagem profunda.

                Orientador: Prof. Dr. Glauco Estácio Gonçalves

                Coorientador: Prof. Dr. Victor Wanderley Costa de Medeiros

      - layout: left
        title: Bacharelado em Ciência da Computação
        caption: 2012 - 2016
        sub_title: Universidade Federal Rural de Pernambuco
        description: | # this will include new lines to allow paragraphs
                Método para identificação da veracidade em impressões digitais utilizando características de alta dimensão.

                Orientador: Luis Filipe Alves Pereira

                Aluno laureado (8.43)

  - title: Concursos # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TJRN
        caption: 2023
        sub_title: Analista Judiciário - Análise de Suporte
        description: | # this will include new lines to allow paragraphs
                Órgão: Tribunal de Justiça do Rio Grande do Norte

                14º colocado
      - layout: left
        title: TRT-13
        caption: 2022
        sub_title: Analista Judiciário - Tecnologia da Informação
        description: | # this will include new lines to allow paragraphs
                Órgão: Tribunal Regional do Trabalho da 13ª Região

                20º colocado
      - layout: left
        title: TRT-6
        caption: 2018
        sub_title: Analista Judiciário - Tecnologia da Informação
        description: | # this will include new lines to allow paragraphs
                Órgão: Tribunal Regional do Trabalho da 6ª Região

                16º colocado
      - layout: left
        title: UFRPE
        caption: 2018
        sub_title: 'Analista de Tecnologia da Informação/Área: Suporte e Rede'
        description: | # this will include new lines to allow paragraphs
                Órgão: Universidade Federal Rural de Pernambuco

                2º colocado
      - layout: left
        title: Compesa
        caption: 2018
        sub_title: Analista de Gestão - Tecnologia da Informação
        description: | # this will include new lines to allow paragraphs
                Órgão: Companhia Pernambucana de Saneamento

                1º colocado
      - layout: left
        title: TJPE
        caption: 2017
        sub_title: Analista Judiciário - Analista de Sistemas
        description: | # this will include new lines to allow paragraphs
                Órgão: Tribunal da Justiça de Pernambuco

                25º colocado
      - layout: left
        title: Embasa
        caption: 2017
        sub_title: Analista de Saneamento - Analista de Tecnologia da Informação (Desenvolvimento)
        description: | # this will include new lines to allow paragraphs
                Meu primeiro concurso de TI.

                Órgão: Empresa Baiana de Águas e Saneamento S.A.

                17º colocado
  - title: Um pouco mais sobre mim
    layout: text
    content: | # this will include new lines to allow paragraphs
      Além da computação, alguns dos meus outros interesses e hobbies são:
      - Música 🎸
      - Leitura 📚
      - Educação financeira 🏦
      - Astronomia 🔭🪐

# Footer
footer_show_references: true
references_title: 🖖🏻

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
